services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: metakgporg/gyft-api-dev
    container_name: gyft-api-dev
    ports:
      - "8000:8000"
    networks:
      - gyft-api-dev-network

networks:
  gyft-api-dev-network:
    name: gyft-api-dev
    driver: bridge
